name: Docker Image CI

on:
  push:
    branches: [ AlphaReleaseV0.1 ]
  pull_request:
    branches: [ AlphaReleaseV0.1 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: run all tests
      run: test Tests
      
    - name: Build and Push
    - uses: tvrcgo/deploy-to-docker@v0.3.1
      with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: 694200109/usersystem:current
